repos:
- repo: https://github.com/pre-commit/pre-commit-hooks
  rev: v4.6.0
  hooks:
  - id: trailing-whitespace
  - id: end-of-file-fixer
  - id: check-ast
- repo: https://github.com/charliermarsh/ruff-pre-commit
  rev: 'v0.2.1'
  hooks:
  - id: ruff
    args: [ --fix, --exit-non-zero-on-fix ]
  - id: ruff-format
- repo: https://github.com/pre-commit/pygrep-hooks
  rev: v1.10.0
  hooks:
  - id: python-use-type-annotations